# Adapted from https://github.com/ChrisPenner/haskell-stack-travis-ci
language: minimal
sudo: true

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1 BUILD_BINARY=1
      compiler: ": #stack 8.2.1"
    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1-osx BUILD_BINARY=1
           STACK_OPTS="--extra-include-dirs=/usr/local/opt/readline/include --extra-lib-dirs=/usr/local/opt/readline/lib"
      os: osx
      compiler: ": #stack 8.2.1"

install:
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis/install-libsecp256k1.sh
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh

script:
 - echo "$(stack ghc -- --version) [$(stack ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - STACK_OPTS="$STACK_OPTS --extra-include-dirs=/usr/local/include --extra-lib-dirs=/usr/local/lib"
 - |
   set -ex
   # Run tests
   stack --no-terminal test --ghc-options="$GHC_OPTIONS" $STACK_OPTS
   set +ex

after_success:
 - |
   # Build and ship binary
   export BUILD_BINARY=true
   export TRAVIS_TAG=$(git rev-parse HEAD)
   ./.travis/attach-binary.sh

notifications:
  email: false
