name: echidna

author: JP Smith

version: 0.0.0.1

ghc-options: -Wall

dependencies:
  - base
  - bytestring >= 0.10.8 && < 0.11
  - containers >= 0.5.7  && < 0.6
  - data-dword >= 0.3.1  && < 0.4
  - exceptions >= 0.8.1  && < 0.9
  - hedgehog
  - hevm
  - lens       >= 4.15.1 && < 4.16
  - mtl        >= 2.2.1  && < 2.3
  - process    >= 1.4.3  && < 1.5
  - temporary  >= 1.2.1  && < 1.3
  - text       >= 1.2.2  && < 1.3
  - vector     >= 0.11.0 && < 0.13

default-extensions:
  - OverloadedStrings

library:
  source-dirs: lib/

executables:
  echidna-test:
    main: Main.hs
    source-dirs: src/
    dependencies: echidna
  simple-example-exe:
    main: Simple.hs
    source-dirs: examples/
    dependencies: echidna
