resolver: lts-16.31

packages:
- '.'

extra-deps:
- git: https://github.com/dapphub/dapptools.git
  commit: 6314bc8e168fce17290a73700a1246f549e2e052
  subdirs:
  - src/hevm

- cryptonite-0.27
- ghci-pretty-0.0.2
- HSH-2.1.3
- monoidal-containers-0.6.0.1
- restless-git-0.7
- s-cargot-0.1.4.0
- text-format-0.3.2
- these-1.0.1
- tree-view-0.5
- sbv-8.9
- witherable-0.3.5
- witherable-class-0
- github: dmjio/semver-range
  commit: d8d9db892ddb6ae267c9bcbc4f6602668433f12a

extra-include-dirs:
- /usr/local/opt/readline/include

extra-lib-dirs:
- /usr/local/opt/readline/lib
